name: 'discord-action'
description: 'Send a message to a Discord webhook'
branding:
  color: 'purple'
  icon: 'message-circle'
inputs:
  webhook:
    description: 'Discord webhook URL'
    required: true
  message:
    description: 'Message to send to Discord'
    required: true
runs:
  using: 'node20'
  main: 'index.js'